name: Build website

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@v3
    -
      uses: actions/setup-node@v3
    -
      run: npm ci
    -
      run: npm run build
    -
      uses: actions/upload-artifact@v3
      with:
        path: build
    -
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      if: github.ref == 'refs/heads/main'
      with:
        branch: gh-pages
        folder: build
        git-config-name: GitHub Actions
        git-config-email: github-actions[bot]@users.noreply.github.com
